name: E2E Tests

on:
  push:
  pull_request:

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install kind
        run: |
          mkdir -p .bin
          curl -fsSLo .bin/kind \
            https://kind.sigs.k8s.io/dl/v0.31.0/kind-linux-amd64
          chmod +x .bin/kind
          echo "$PWD/.bin" >> "$GITHUB_PATH"
          .bin/kind version

      - name: Running Test e2e
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum
          make test-e2e
